spring:
  thymeleaf:
    cache: false

  mail:
    default-encoding: UTF-8
    host: smtp.naver.com
    port: 465
    username: ${NAVER_EMAIL_USERNAME}
    password: ${NAVER_EMAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF-8
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
