version: "3"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    image: sjiwon/study-with-me-be:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - "./logs:/logs"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus-prod.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - "./monitoring/grafana_data:/var/lib/grafana"
    depends_on:
      - prometheus
    privileged: true

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - "./logs:/logs"
      - "./promtail-prod.yml:/etc/promtail/config.yml"
    command: -config.file=/etc/promtail/config.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
