version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
