version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    image: sjiwon/study-with-me-be:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
