spring:
  config:
    import:
      - settings/application-jpa.yml
      - settings/application-cloud.yml
      - settings/application-mail.yml
      - settings/application-oauth.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/study_with_me?autoReconnect=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  access-token-validity: 7200
  refresh-token-validity: 1209600

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    org.springframework.core:
      LocalVariableTableParameterNameDiscoverer: error
