spring:
  config:
    import:
      - settings/application-jpa.yml
      - settings/application-cloud.yml
      - settings/application-mail.yml
      - settings/application-oauth.yml

  datasource:
    driver-class-name: ${RDS_DRIVER}
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity: 7200 # 2시간
  refresh-token-validity: 1209600 # 2주

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

logging:
  level:
    org.springframework.core:
      LocalVariableTableParameterNameDiscoverer: error

decorator:
  datasource:
    p6spy:
      enable-logging: false
