spring:
  config:
    import:
      - settings/application-logging.yml
      - settings/application-data.yml
      - settings/application-external.yml
      - settings/application-mail.yml
      - settings/application-oauth.yml
      - settings/application-cloud.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/study_with_me?autoReconnect=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: 2da7acad220ffe59e6943c826ec1fcf879a4339521ff5837fa92aab485e94bcb # 테스트용 Secret Key
  access-token-validity: 7200
  refresh-token-validity: 1209600

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

decorator:
  datasource:
    p6spy:
      enable-logging: true
