positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: info
    static_configs:
      - targets:
          - host.docker.internal
        labels:
          job: info_logs
          __path__: ./logs/info/*.log

  - job_name: warn
    static_configs:
      - targets:
          - host.docker.internal
        labels:
          job: warn_logs
          __path__: ./logs/warn/*.log

  - job_name: error
    static_configs:
      - targets:
          - host.docker.internal
        labels:
          job: error_logs
          __path__: ./logs/error/*.log
