name: Backend CD

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: [ "Backend CI" ]
    types:
      - completed

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Repository를 가져온다
        uses: actions/checkout@v3

      - name: JDK 17을 설치한다
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Gradle 정보를 캐싱한다
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Timezone을 Asia/Seoul로 설정한다
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Gradle 명령 실행을 위한 권한을 부여한다
        run: chmod +x gradlew

      - name: Gradle build를 수행한다 (테스트 제외)
        run: ./gradlew bootJar -x test

      - name: Docker Image를 빌드한 후 Docker Hub에 Push한다
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/study-with-me-be:latest .
          docker images
          docker push ${{ secrets.DOCKER_USERNAME }}/study-with-me-be:latest

      - name: EC2 WAS 서버에 접속 후 Docker Image를 Pull하고 docker-compose를 실행한다
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker rm -f $(docker ps -qa)
            docker rmi ${{ secrets.DOCKER_USERNAME }}/study-with-me-be:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/study-with-me-be:latest
            docker-compose -f docker-compose-prod.yml up -d
